### ISSUE TITLE
Disabling constellation-dependent bonus by lowering constellation doesn't reset effect

### ISSUE THREAD

**Issue by jktrn** [jktrn/screenshot-impact#23]
Even though it may display as "off" whenever it's disabled through removing constellations, the effect is still being applied.

**Comment by flocto** [comment]
Bug occurs because some Constellation bonuses are defined in `characterBonuses.tsx` instead of `constellationBonuses.tsx`. When removing/adding constellations, the activeBonuses is not properly updated according to these constellations/bonuses.

Possible fixes:
- Completely rework bonus/constellation system, possibly merge both Bonuses into one file
- Add specific attribute in constellations to check if they have separate associated characterBonus to remove/modify

**Comment by jktrn** [comment]
Resolved.
